//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Astros.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class astrosEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new astrosEntities object using the connection string found in the 'astrosEntities' section of the application configuration file.
        /// </summary>
        public astrosEntities() : base("name=astrosEntities", "astrosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new astrosEntities object.
        /// </summary>
        public astrosEntities(string connectionString) : base(connectionString, "astrosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new astrosEntities object.
        /// </summary>
        public astrosEntities(EntityConnection connection) : base(connection, "astrosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<league_adjustment> league_adjustment
        {
            get
            {
                if ((_league_adjustment == null))
                {
                    _league_adjustment = base.CreateObjectSet<league_adjustment>("league_adjustment");
                }
                return _league_adjustment;
            }
        }
        private ObjectSet<league_adjustment> _league_adjustment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<park_factor> park_factor
        {
            get
            {
                if ((_park_factor == null))
                {
                    _park_factor = base.CreateObjectSet<park_factor>("park_factor");
                }
                return _park_factor;
            }
        }
        private ObjectSet<park_factor> _park_factor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<player_splits> player_splits
        {
            get
            {
                if ((_player_splits == null))
                {
                    _player_splits = base.CreateObjectSet<player_splits>("player_splits");
                }
                return _player_splits;
            }
        }
        private ObjectSet<player_splits> _player_splits;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<player_stats> player_stats
        {
            get
            {
                if ((_player_stats == null))
                {
                    _player_stats = base.CreateObjectSet<player_stats>("player_stats");
                }
                return _player_stats;
            }
        }
        private ObjectSet<player_stats> _player_stats;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<roster> rosters
        {
            get
            {
                if ((_rosters == null))
                {
                    _rosters = base.CreateObjectSet<roster>("rosters");
                }
                return _rosters;
            }
        }
        private ObjectSet<roster> _rosters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rosters_lahman> rosters_lahman
        {
            get
            {
                if ((_rosters_lahman == null))
                {
                    _rosters_lahman = base.CreateObjectSet<rosters_lahman>("rosters_lahman");
                }
                return _rosters_lahman;
            }
        }
        private ObjectSet<rosters_lahman> _rosters_lahman;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<park> parks
        {
            get
            {
                if ((_parks == null))
                {
                    _parks = base.CreateObjectSet<park>("parks");
                }
                return _parks;
            }
        }
        private ObjectSet<park> _parks;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the league_adjustment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToleague_adjustment(league_adjustment league_adjustment)
        {
            base.AddObject("league_adjustment", league_adjustment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the park_factor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopark_factor(park_factor park_factor)
        {
            base.AddObject("park_factor", park_factor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the player_splits EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToplayer_splits(player_splits player_splits)
        {
            base.AddObject("player_splits", player_splits);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the player_stats EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToplayer_stats(player_stats player_stats)
        {
            base.AddObject("player_stats", player_stats);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rosters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorosters(roster roster)
        {
            base.AddObject("rosters", roster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rosters_lahman EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorosters_lahman(rosters_lahman rosters_lahman)
        {
            base.AddObject("rosters_lahman", rosters_lahman);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the parks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToparks(park park)
        {
            base.AddObject("parks", park);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="astrosModel", Name="league_adjustment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class league_adjustment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new league_adjustment object.
        /// </summary>
        /// <param name="league">Initial value of the league property.</param>
        /// <param name="season">Initial value of the season property.</param>
        /// <param name="event_code">Initial value of the event_code property.</param>
        public static league_adjustment Createleague_adjustment(global::System.String league, global::System.Int32 season, global::System.String event_code)
        {
            league_adjustment league_adjustment = new league_adjustment();
            league_adjustment.league = league;
            league_adjustment.season = season;
            league_adjustment.event_code = event_code;
            return league_adjustment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String league
        {
            get
            {
                return _league;
            }
            set
            {
                if (_league != value)
                {
                    OnleagueChanging(value);
                    ReportPropertyChanging("league");
                    _league = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("league");
                    OnleagueChanged();
                }
            }
        }
        private global::System.String _league;
        partial void OnleagueChanging(global::System.String value);
        partial void OnleagueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 season
        {
            get
            {
                return _season;
            }
            set
            {
                if (_season != value)
                {
                    OnseasonChanging(value);
                    ReportPropertyChanging("season");
                    _season = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("season");
                    OnseasonChanged();
                }
            }
        }
        private global::System.Int32 _season;
        partial void OnseasonChanging(global::System.Int32 value);
        partial void OnseasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String event_code
        {
            get
            {
                return _event_code;
            }
            set
            {
                if (_event_code != value)
                {
                    Onevent_codeChanging(value);
                    ReportPropertyChanging("event_code");
                    _event_code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("event_code");
                    Onevent_codeChanged();
                }
            }
        }
        private global::System.String _event_code;
        partial void Onevent_codeChanging(global::System.String value);
        partial void Onevent_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> factor
        {
            get
            {
                return _factor;
            }
            set
            {
                OnfactorChanging(value);
                ReportPropertyChanging("factor");
                _factor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("factor");
                OnfactorChanged();
            }
        }
        private Nullable<global::System.Decimal> _factor;
        partial void OnfactorChanging(Nullable<global::System.Decimal> value);
        partial void OnfactorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> multiplier
        {
            get
            {
                return _multiplier;
            }
            set
            {
                OnmultiplierChanging(value);
                ReportPropertyChanging("multiplier");
                _multiplier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("multiplier");
                OnmultiplierChanged();
            }
        }
        private Nullable<global::System.Decimal> _multiplier;
        partial void OnmultiplierChanging(Nullable<global::System.Decimal> value);
        partial void OnmultiplierChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="astrosModel", Name="park")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class park : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new park object.
        /// </summary>
        /// <param name="site_id">Initial value of the site_id property.</param>
        public static park Createpark(global::System.String site_id)
        {
            park park = new park();
            park.site_id = site_id;
            return park;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String site_id
        {
            get
            {
                return _site_id;
            }
            set
            {
                if (_site_id != value)
                {
                    Onsite_idChanging(value);
                    ReportPropertyChanging("site_id");
                    _site_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("site_id");
                    Onsite_idChanged();
                }
            }
        }
        private global::System.String _site_id;
        partial void Onsite_idChanging(global::System.String value);
        partial void Onsite_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="astrosModel", Name="park_factor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class park_factor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new park_factor object.
        /// </summary>
        /// <param name="site_id">Initial value of the site_id property.</param>
        /// <param name="event_code">Initial value of the event_code property.</param>
        public static park_factor Createpark_factor(global::System.String site_id, global::System.String event_code)
        {
            park_factor park_factor = new park_factor();
            park_factor.site_id = site_id;
            park_factor.event_code = event_code;
            return park_factor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String site_id
        {
            get
            {
                return _site_id;
            }
            set
            {
                if (_site_id != value)
                {
                    Onsite_idChanging(value);
                    ReportPropertyChanging("site_id");
                    _site_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("site_id");
                    Onsite_idChanged();
                }
            }
        }
        private global::System.String _site_id;
        partial void Onsite_idChanging(global::System.String value);
        partial void Onsite_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String event_code
        {
            get
            {
                return _event_code;
            }
            set
            {
                if (_event_code != value)
                {
                    Onevent_codeChanging(value);
                    ReportPropertyChanging("event_code");
                    _event_code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("event_code");
                    Onevent_codeChanged();
                }
            }
        }
        private global::System.String _event_code;
        partial void Onevent_codeChanging(global::System.String value);
        partial void Onevent_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> factor
        {
            get
            {
                return _factor;
            }
            set
            {
                OnfactorChanging(value);
                ReportPropertyChanging("factor");
                _factor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("factor");
                OnfactorChanged();
            }
        }
        private Nullable<global::System.Decimal> _factor;
        partial void OnfactorChanging(Nullable<global::System.Decimal> value);
        partial void OnfactorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> multiplier
        {
            get
            {
                return _multiplier;
            }
            set
            {
                OnmultiplierChanging(value);
                ReportPropertyChanging("multiplier");
                _multiplier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("multiplier");
                OnmultiplierChanged();
            }
        }
        private Nullable<global::System.Decimal> _multiplier;
        partial void OnmultiplierChanging(Nullable<global::System.Decimal> value);
        partial void OnmultiplierChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="astrosModel", Name="player_splits")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class player_splits : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new player_splits object.
        /// </summary>
        /// <param name="retro_id">Initial value of the retro_id property.</param>
        /// <param name="season">Initial value of the season property.</param>
        public static player_splits Createplayer_splits(global::System.String retro_id, global::System.Int32 season)
        {
            player_splits player_splits = new player_splits();
            player_splits.retro_id = retro_id;
            player_splits.season = season;
            return player_splits;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String retro_id
        {
            get
            {
                return _retro_id;
            }
            set
            {
                if (_retro_id != value)
                {
                    Onretro_idChanging(value);
                    ReportPropertyChanging("retro_id");
                    _retro_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("retro_id");
                    Onretro_idChanged();
                }
            }
        }
        private global::System.String _retro_id;
        partial void Onretro_idChanging(global::System.String value);
        partial void Onretro_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 season
        {
            get
            {
                return _season;
            }
            set
            {
                if (_season != value)
                {
                    OnseasonChanging(value);
                    ReportPropertyChanging("season");
                    _season = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("season");
                    OnseasonChanged();
                }
            }
        }
        private global::System.Int32 _season;
        partial void OnseasonChanging(global::System.Int32 value);
        partial void OnseasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> split
        {
            get
            {
                return _split;
            }
            set
            {
                OnsplitChanging(value);
                ReportPropertyChanging("split");
                _split = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("split");
                OnsplitChanged();
            }
        }
        private Nullable<global::System.Decimal> _split;
        partial void OnsplitChanging(Nullable<global::System.Decimal> value);
        partial void OnsplitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String formula
        {
            get
            {
                return _formula;
            }
            set
            {
                OnformulaChanging(value);
                ReportPropertyChanging("formula");
                _formula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("formula");
                OnformulaChanged();
            }
        }
        private global::System.String _formula;
        partial void OnformulaChanging(global::System.String value);
        partial void OnformulaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="astrosModel", Name="player_stats")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class player_stats : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new player_stats object.
        /// </summary>
        /// <param name="retro_id">Initial value of the retro_id property.</param>
        /// <param name="season">Initial value of the season property.</param>
        /// <param name="vs_pitcher_side">Initial value of the vs_pitcher_side property.</param>
        public static player_stats Createplayer_stats(global::System.String retro_id, global::System.Int32 season, global::System.String vs_pitcher_side)
        {
            player_stats player_stats = new player_stats();
            player_stats.retro_id = retro_id;
            player_stats.season = season;
            player_stats.vs_pitcher_side = vs_pitcher_side;
            return player_stats;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String retro_id
        {
            get
            {
                return _retro_id;
            }
            set
            {
                if (_retro_id != value)
                {
                    Onretro_idChanging(value);
                    ReportPropertyChanging("retro_id");
                    _retro_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("retro_id");
                    Onretro_idChanged();
                }
            }
        }
        private global::System.String _retro_id;
        partial void Onretro_idChanging(global::System.String value);
        partial void Onretro_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 season
        {
            get
            {
                return _season;
            }
            set
            {
                if (_season != value)
                {
                    OnseasonChanging(value);
                    ReportPropertyChanging("season");
                    _season = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("season");
                    OnseasonChanged();
                }
            }
        }
        private global::System.Int32 _season;
        partial void OnseasonChanging(global::System.Int32 value);
        partial void OnseasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vs_pitcher_side
        {
            get
            {
                return _vs_pitcher_side;
            }
            set
            {
                if (_vs_pitcher_side != value)
                {
                    Onvs_pitcher_sideChanging(value);
                    ReportPropertyChanging("vs_pitcher_side");
                    _vs_pitcher_side = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("vs_pitcher_side");
                    Onvs_pitcher_sideChanged();
                }
            }
        }
        private global::System.String _vs_pitcher_side;
        partial void Onvs_pitcher_sideChanging(global::System.String value);
        partial void Onvs_pitcher_sideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> pa
        {
            get
            {
                return _pa;
            }
            set
            {
                OnpaChanging(value);
                ReportPropertyChanging("pa");
                _pa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pa");
                OnpaChanged();
            }
        }
        private Nullable<global::System.Decimal> _pa;
        partial void OnpaChanging(Nullable<global::System.Decimal> value);
        partial void OnpaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> singles
        {
            get
            {
                return _singles;
            }
            set
            {
                OnsinglesChanging(value);
                ReportPropertyChanging("singles");
                _singles = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("singles");
                OnsinglesChanged();
            }
        }
        private Nullable<global::System.Decimal> _singles;
        partial void OnsinglesChanging(Nullable<global::System.Decimal> value);
        partial void OnsinglesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> doubles
        {
            get
            {
                return _doubles;
            }
            set
            {
                OndoublesChanging(value);
                ReportPropertyChanging("doubles");
                _doubles = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("doubles");
                OndoublesChanged();
            }
        }
        private Nullable<global::System.Decimal> _doubles;
        partial void OndoublesChanging(Nullable<global::System.Decimal> value);
        partial void OndoublesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> triples
        {
            get
            {
                return _triples;
            }
            set
            {
                OntriplesChanging(value);
                ReportPropertyChanging("triples");
                _triples = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("triples");
                OntriplesChanged();
            }
        }
        private Nullable<global::System.Decimal> _triples;
        partial void OntriplesChanging(Nullable<global::System.Decimal> value);
        partial void OntriplesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> homeruns
        {
            get
            {
                return _homeruns;
            }
            set
            {
                OnhomerunsChanging(value);
                ReportPropertyChanging("homeruns");
                _homeruns = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("homeruns");
                OnhomerunsChanged();
            }
        }
        private Nullable<global::System.Decimal> _homeruns;
        partial void OnhomerunsChanging(Nullable<global::System.Decimal> value);
        partial void OnhomerunsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> walks
        {
            get
            {
                return _walks;
            }
            set
            {
                OnwalksChanging(value);
                ReportPropertyChanging("walks");
                _walks = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("walks");
                OnwalksChanged();
            }
        }
        private Nullable<global::System.Decimal> _walks;
        partial void OnwalksChanging(Nullable<global::System.Decimal> value);
        partial void OnwalksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> hitbypitch
        {
            get
            {
                return _hitbypitch;
            }
            set
            {
                OnhitbypitchChanging(value);
                ReportPropertyChanging("hitbypitch");
                _hitbypitch = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hitbypitch");
                OnhitbypitchChanged();
            }
        }
        private Nullable<global::System.Decimal> _hitbypitch;
        partial void OnhitbypitchChanging(Nullable<global::System.Decimal> value);
        partial void OnhitbypitchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> nonk
        {
            get
            {
                return _nonk;
            }
            set
            {
                OnnonkChanging(value);
                ReportPropertyChanging("nonk");
                _nonk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nonk");
                OnnonkChanged();
            }
        }
        private Nullable<global::System.Decimal> _nonk;
        partial void OnnonkChanging(Nullable<global::System.Decimal> value);
        partial void OnnonkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> strikeouts
        {
            get
            {
                return _strikeouts;
            }
            set
            {
                OnstrikeoutsChanging(value);
                ReportPropertyChanging("strikeouts");
                _strikeouts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("strikeouts");
                OnstrikeoutsChanged();
            }
        }
        private Nullable<global::System.Decimal> _strikeouts;
        partial void OnstrikeoutsChanging(Nullable<global::System.Decimal> value);
        partial void OnstrikeoutsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> batting_average
        {
            get
            {
                return _batting_average;
            }
            set
            {
                Onbatting_averageChanging(value);
                ReportPropertyChanging("batting_average");
                _batting_average = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("batting_average");
                Onbatting_averageChanged();
            }
        }
        private Nullable<global::System.Decimal> _batting_average;
        partial void Onbatting_averageChanging(Nullable<global::System.Decimal> value);
        partial void Onbatting_averageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> on_base_percentage
        {
            get
            {
                return _on_base_percentage;
            }
            set
            {
                Onon_base_percentageChanging(value);
                ReportPropertyChanging("on_base_percentage");
                _on_base_percentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("on_base_percentage");
                Onon_base_percentageChanged();
            }
        }
        private Nullable<global::System.Decimal> _on_base_percentage;
        partial void Onon_base_percentageChanging(Nullable<global::System.Decimal> value);
        partial void Onon_base_percentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ops
        {
            get
            {
                return _ops;
            }
            set
            {
                OnopsChanging(value);
                ReportPropertyChanging("ops");
                _ops = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ops");
                OnopsChanged();
            }
        }
        private Nullable<global::System.Decimal> _ops;
        partial void OnopsChanging(Nullable<global::System.Decimal> value);
        partial void OnopsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="astrosModel", Name="roster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class roster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new roster object.
        /// </summary>
        /// <param name="retro_id">Initial value of the retro_id property.</param>
        public static roster Createroster(global::System.String retro_id)
        {
            roster roster = new roster();
            roster.retro_id = retro_id;
            return roster;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String retro_id
        {
            get
            {
                return _retro_id;
            }
            set
            {
                if (_retro_id != value)
                {
                    Onretro_idChanging(value);
                    ReportPropertyChanging("retro_id");
                    _retro_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("retro_id");
                    Onretro_idChanged();
                }
            }
        }
        private global::System.String _retro_id;
        partial void Onretro_idChanging(global::System.String value);
        partial void Onretro_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                Onlast_nameChanging(value);
                ReportPropertyChanging("last_name");
                _last_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("last_name");
                Onlast_nameChanged();
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String throw_side
        {
            get
            {
                return _throw_side;
            }
            set
            {
                Onthrow_sideChanging(value);
                ReportPropertyChanging("throw_side");
                _throw_side = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("throw_side");
                Onthrow_sideChanged();
            }
        }
        private global::System.String _throw_side;
        partial void Onthrow_sideChanging(global::System.String value);
        partial void Onthrow_sideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bat_side
        {
            get
            {
                return _bat_side;
            }
            set
            {
                Onbat_sideChanging(value);
                ReportPropertyChanging("bat_side");
                _bat_side = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bat_side");
                Onbat_sideChanged();
            }
        }
        private global::System.String _bat_side;
        partial void Onbat_sideChanging(global::System.String value);
        partial void Onbat_sideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String team_id
        {
            get
            {
                return _team_id;
            }
            set
            {
                Onteam_idChanging(value);
                ReportPropertyChanging("team_id");
                _team_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("team_id");
                Onteam_idChanged();
            }
        }
        private global::System.String _team_id;
        partial void Onteam_idChanging(global::System.String value);
        partial void Onteam_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String position
        {
            get
            {
                return _position;
            }
            set
            {
                OnpositionChanging(value);
                ReportPropertyChanging("position");
                _position = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("position");
                OnpositionChanged();
            }
        }
        private global::System.String _position;
        partial void OnpositionChanging(global::System.String value);
        partial void OnpositionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="astrosModel", Name="rosters_lahman")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rosters_lahman : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rosters_lahman object.
        /// </summary>
        /// <param name="retro_id">Initial value of the retro_id property.</param>
        public static rosters_lahman Createrosters_lahman(global::System.String retro_id)
        {
            rosters_lahman rosters_lahman = new rosters_lahman();
            rosters_lahman.retro_id = retro_id;
            return rosters_lahman;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String retro_id
        {
            get
            {
                return _retro_id;
            }
            set
            {
                if (_retro_id != value)
                {
                    Onretro_idChanging(value);
                    ReportPropertyChanging("retro_id");
                    _retro_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("retro_id");
                    Onretro_idChanged();
                }
            }
        }
        private global::System.String _retro_id;
        partial void Onretro_idChanging(global::System.String value);
        partial void Onretro_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> lahman_id
        {
            get
            {
                return _lahman_id;
            }
            set
            {
                Onlahman_idChanging(value);
                ReportPropertyChanging("lahman_id");
                _lahman_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lahman_id");
                Onlahman_idChanged();
            }
        }
        private Nullable<global::System.Int32> _lahman_id;
        partial void Onlahman_idChanging(Nullable<global::System.Int32> value);
        partial void Onlahman_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> birth_date
        {
            get
            {
                return _birth_date;
            }
            set
            {
                Onbirth_dateChanging(value);
                ReportPropertyChanging("birth_date");
                _birth_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("birth_date");
                Onbirth_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _birth_date;
        partial void Onbirth_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onbirth_dateChanged();

        #endregion
    
    }

    #endregion
    
}
